/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Mutterings {
  category: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reply: string | null;
  user_id: string;
}

export interface Profiles {
  created_at: Generated<Timestamp>;
  intensity_level: Generated<string>;
  last_review_month: string | null;
  user_id: string;
}

export interface Seeds {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  muttering_id: string;
  nudged_at: Timestamp | null;
  parent_id: string | null;
  processed_task: string;
  prophecy: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DB {
  mutterings: Mutterings;
  profiles: Profiles;
  seeds: Seeds;
}
